### ISSUE TITLE
Only Supports Dance Single Charts?

### ISSUE THREAD

**Issue by HappyJuiceLive** [ABuffSeagull/CloneMania#1]
I'd like to convert my custom Stepmania.sm charts to play in Clone Hero, but unfortunately this converter seems to only accept charts that are dance-single, which is limited to only 4 lanes.

I can trick it by editing the .sm file to call them all dance-single, but then I can only convert up to 4 charts at a time, as a single instrument. (and the 5th lane is always empty)

I'd like to be able to take dance-single, and call that the Guitar.
And the pump-single charts to be imported as the Bass
pump-double as the Drums, etc etc

**Comment by ABuffSeagull** [comment]
Unfortunately this project was never completed (probably should make a readme), so there's no guarantee even the simplest songs can work.
There's almost no chance I'll ever come back to this, so feel free to fork it, or otherwise look for another tool somewhere else.

**Comment by HappyJuiceLive** [comment]
Thanks for the reply!

I tinkered around with it for a bit and actually found a way to make it work :)

You basically have to do a ctrl+H find "dance-single" in your script and replace with "dance-double".

Then in your .sm file, make sure all charts are marked as dance double. 5 lane conversion with multiple instruments! (if you then go into your newly generated notes.chart and rename their respective instruments) (DoubleBass, Single, etc)
